### ISSUE TITLE
Running two pushes at the same time causes duplicate files created even with --update

### ISSUE THREAD

**Issue by NickFirmani** [Qordobacode/qordoba-cli#69]
**Problem cause:** 
We have a CI job that spins up a container for any commit to master, and runs `qor push --update`. Last night I committed two commits very close to each other, which caused two jobs to run at approximately the same time. 

**Results:**
Duplicate files with the same name in the Dashboard 
<img width="995" alt="screen shot 2018-07-03 at 2 11 18 pm" src="https://user-images.githubusercontent.com/4187433/42244741-01f9c8ee-7ecb-11e8-93c5-c13614986cec.png">

**Simplified reproduction steps:**
Run: 
`qor push --update & qor push --update`

Example `.qordoba.yml` and example file `strings.xml`
```
qordoba: 
  access_token: xyz
  organization_id: abc
  project_id: def

  push:
    sources:
    - "strings.xml" 
```
```
<resources>
  <string name="app_name">Test App</string>
</resources>
```

**Expected result:** 
Either both succeed, sequentially, or one fails, or both fails. I'm not picky on the resultant behavior, since it won't really affect our pipeline.
